<%
'======================================================
' Limpando caracteres especiais
'======================================================
Function Limpar_Texto(campo)
	limpar = campo
	limpar = Replace(limpar, "'", "''")
	limpar = Replace(limpar, "--", "")
	limpar = Replace(limpar, "&lt;", "<")
	limpar = Replace(limpar, "&gt;", ">")	
	limpar = Replace(limpar, "&amp;", "&")
	limpar = Replace(limpar, "&nbsp;", " ")
	limpar = Replace(limpar, "&ndash;", "–")
	limpar = Replace(limpar, "&mdash;", "—")
	limpar = Replace(limpar, "&hellip;", "…")
	limpar = Replace(limpar, "&bull;", "&bull;")
	limpar = Replace(limpar, "&sect;", "&sect;")
	limpar = Replace(limpar, "&copy;", "©")
	limpar = Replace(limpar, "&reg", "®")
	limpar = Replace(limpar, "&ordf;", "ª")
	
	
	limpar = Replace(limpar, "&aacute;", "á") 
	limpar = Replace(limpar, "&Aacute;", "Á") 
	limpar = Replace(limpar, "&atilde;", "ã") 
	limpar = Replace(limpar, "&Atilde;", "Ã") 
	limpar = Replace(limpar, "&acirc;", "â")
	limpar = Replace(limpar, "&Acirc;", "Â")
	limpar = Replace(limpar, "&agrave;", "à")
	limpar = Replace(limpar, "&Agrave;", "À") 
	limpar = Replace(limpar, "&eacute;", "é")
	limpar = Replace(limpar, "&Eacute;", "É")
	limpar = Replace(limpar, "&ecirc;", "ê")
	limpar = Replace(limpar, "&Ecirc;", "Ê") 
	limpar = Replace(limpar, "&iacute;", "í")
	limpar = Replace(limpar, "&Iacute;", "Í")
	limpar = Replace(limpar, "&oacute;", "ó")
	limpar = Replace(limpar, "&Oacute;", "Ó") 
	limpar = Replace(limpar, "&otilde;", "õ") 
	limpar = Replace(limpar, "&Otilde;", "Õ") 
	limpar = Replace(limpar, "&ocirc;", "ô") 
	limpar = Replace(limpar, "&Ocirc;", "Ô") 
	limpar = Replace(limpar, "&uacute;", "ú")
	limpar = Replace(limpar, "&Uacute;", "Ú")
	limpar = Replace(limpar, "&uuml;", "ü")
	limpar = Replace(limpar, "&Uuml;", "Ü") 
	limpar = Replace(limpar, "&ccedil;", "ç")
	limpar = Replace(limpar, "&Ccedil;", "Ç") 
	limpar = Replace(limpar, "&ntilde;", "ñ") 	
	limpar = Replace(limpar, "&Ntilde;", "Ñ") 	
	limpar = Replace(limpar, "&quot;", """")
	limpar = Replace(limpar, "insert ", "")
	limpar = Replace(limpar, "update ", "")
	limpar = Replace(limpar, "select ", "")
	limpar = Replace(limpar, "delete ", "")
	limpar = Replace(limpar, "set ", "")
	limpar = Replace(limpar, "values ", "")
	Limpar_Texto = limpar
End Function
%>